# Generated by Django 6.0 on 2026-01-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="myapp.customer",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="salesperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="myapp.salesperson",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="total",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
