# Generated by Django 6.0 on 2026-01-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_invoice_customer_alter_invoice_salesperson_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="type",
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("wholesale", "Wholesale"),
                    ("distributor", "Distributor"),
                ],
                default="retail",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
