# Generated by Django 6.0 on 2026-01-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_customer_type_customer_customer_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesperson",
            name="employee_id",
        ),
        migrations.AlterField(
            model_name="salesperson",
            name="join_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="salesperson",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("cotton", "Cotton"),
                    ("silk", "Silk"),
                    ("synthetic", "Synthetic"),
                    ("wool", "Wool"),
                ],
                max_length=20,
            ),
        ),
    ]
