# Generated by Django 6.0 on 2026-01-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_remove_salesperson_employee_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("meter", "Meter"),
                    ("piece", "Piece"),
                    ("litre", "Litre"),
                ],
                max_length=20,
            ),
        ),
    ]
