# Generated by Django 6.0 on 2026-01-14 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_product_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.customer"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="sale_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="salesperson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.salesperson"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoiceitems",
                to="myapp.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
