# Generated by Django 6.0 on 2026-01-15 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_invoice_customer_alter_invoice_sale_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="sale_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="salesperson",
            name="join_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
