# Generated by Django 6.0 on 2026-01-21 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_invoice_sale_date_alter_invoiceitem_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NextMonthPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_amount", models.FloatField()),
                ("confidence", models.FloatField()),
                ("based_on_months", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "salesperson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.salesperson",
                    ),
                ),
            ],
        ),
    ]
